###################################
#   Widelands.org                 #
#                                 #
#   Appveyor build configuration  #
###################################

environment:
  CoverityProjectToken:
    secure: ilVyFbbr7tyi3dzLa+D0v017A52Vgs5O4gf2jYlCWA4=

init:
  - cmd: "IF \"%PLATFORM%\" == \"x86\" (set MINGWPATH=C:\\msys64\\mingw32\\bin& set MINGWSUFFIX=i686) ELSE (set MINGWPATH=C:\\msys64\\mingw64\\bin& set MINGWSUFFIX=x86_64)"

install:
  # Installing various utilities
  - cinst InnoSetup
  - cmd: nuget install PublishCoverity
  - cmd: "set PATH=%MINGWPATH%;C:\\msys64\\usr\\bin;C:\\Program Files (x86)\\Inno Setup 5;%PATH%"
  - cmd: "set CC=%MINGWPATH%\\gcc.exe"
  - cmd: "set CXX=%MINGWPATH%\\g++.exe"
  # Update mirrors
  - cmd: "bash --login -c \"pacman --noconfirm --sync pacman pacman-mirrors\""
  # Update msys2 system (twice, first run does system packages)
  - cmd: "bash --login -c \"pacman -Su --noconfirm\""
  - cmd: "bash --login -c \"pacman -Su --noconfirm\""
  # Installed required libs
  - cmd: "bash --login -c \"pacman --noconfirm -S mingw-w64-%MINGWSUFFIX%-ninja mingw-w64-%MINGWSUFFIX%-boost mingw-w64-%MINGWSUFFIX%-SDL2_net mingw-w64-%MINGWSUFFIX%-SDL2_ttf mingw-w64-%MINGWSUFFIX%-SDL2_mixer mingw-w64-%MINGWSUFFIX%-SDL2_image mingw-w64-%MINGWSUFFIX%-glbinding\""

shallow_clone: true

branches:
  except:
    - _widelands_dev_widelands_trunk
    - coverity_scan

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: md build
  - cmd: cd build
  - cmd: echo %APPVEYOR_BUILD_VERSION%_%CONFIGURATION%_%PLATFORM% > %APPVEYOR_BUILD_FOLDER%\WL_RELEASE
  - cmd: "cmake -G \"Ninja\" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DOPTION_USE_GLBINDING=ON %APPVEYOR_BUILD_FOLDER%"
  - cmd: cov-build --dir cov-int ninja
  - cmd: PublishCoverity compress -o coverity.zip -i cov-int
  - cmd: PublishCoverity publish -z coverity.zip -r widelands/widelands -t %CoverityProjectToken% -d "AppVeyor scheduled build." --codeVersion %APPVEYOR_BUILD_VERSION%

platform: 
  - x64

configuration:
  - Release
  